apiVersion: batch/v1
kind: CronJob
metadata:
  name: producer
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: producer
            image: jonnaymt/ssc-producer:1
            imagePullPolicy: Always
          restartPolicy: Never
