apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        imagePullPolicy: Always
        image: jonnaymt/ssc-consumer:0.1.2
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: producer-secret
              key: username
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
